#      _ ____              _     _
#     | |  _ \ _   _ _ __ (_)___| |__
#  _  | | |_) | | | | '_ \| / __| '_ \
# | |_| |  __/| |_| | | | | \__ \ | | |
#  \___/|_|    \__,_|_| |_|_|___/_| |_|
#            Made by jiggey#4704
#
# Please Note: The Items Name Will Be The Kick / Ban / Mute Reason!


# This will set the name and lore of the first item on the BAN MENU. Example: "Non-Malicious Hacks"
banItemOneName: 'Non-Malicious Hacks'
banItemOneLore: 'Derp, SkinBlink, Twerk, Shift, etc.'


# This will set the name and lore of the second item on the BAN MENU.
banItemTwoName: 'Malicious Hacks'
banItemTwoLore: 'KillAura, AutoClicker, Aimbot, etc '


# This will set the name and lore of the third item on the BAN MENU.
banItemThreeName: 'Ban Evasion'
banItemThreeLore: 'Permanent Ban'


# This will set the name and lore of the fourth item on the BAN MENU.
banItemFourName: 'Permanent Ban [Other]'
banItemFourLore: 'For "Other" ban reasons.'


# This Determines All Ban Lengths
banLengthOne: '7d'
banLengthTwo: '30d'
banLengthThree: ''
banLengthFour: ''


# This sets the items for the Ban GUI! The default items are examples,
# you can set this as ANY item name, just make sure its the actual name!
# Examples: DIAMOND_SWORD, DIRT_BLOCK, DIAMOND_BLOCK, etc.
banItemOne: 'GREEN_TERRACOTTA'
banItemTwo: 'DIAMOND_SWORD'
banItemThree: 'ENDER_PEARL'
banItemFour: 'BARRIER'


### THE NEXT SECTION IS FOR THE KICK MENU!

# This will set the name and lore of the first item on the KICK MENU
kickItemOneName: 'KickReasonOne'
kickItemOneLore: 'KickLoreOne'


# This will set the name and lore of the second item on the KICK MENU
kickItemTwoName: 'KickReasonTwo'
kickItemTwoLore: 'KickLoreTwo'


# This will set the name and lore of the third item on the KICK MENU
kickItemThreeName: 'KickReasonThree'
kickItemThreeLore: 'KickLoreThree'


# This sets the items for the Kick GUI! The default items are examples,
# you can set this as ANY item name, just make sure its the actual name!
# Examples: DIAMOND_SWORD, DIRT_BLOCK, DIAMOND_BLOCK, etc.
kickItemOne: 'GREEN_TERRACOTTA'
kickItemTwo: 'ORANGE_TERRACOTTA'
kickItemThree: 'RED_TERRACOTTA'


### THE NEXT SECTION IS FOR THE MUTE MENU!

# This will set the name and lore of the first item on the MUTE MENU
muteItemOneName: 'MuteReasonOne'
muteItemOneLore: 'MuteLoreOne'


# This will set the name and lore of the second item on the MUTE MENU
muteItemTwoName: 'MuteReasonTwo'
muteItemTwoLore: 'MuteLoreTwo'


# This will set the name and lore of the third item on the MUTE MENU
muteItemThreeName: 'MuteReasonThree'
muteItemThreeLore: 'MuteLoreThree'


# This sets the items for the Mute GUI! The default items are examples,
# you can set this as ANY item name, just make sure its the actual name!
# Examples: DIAMOND_SWORD, DIRT_BLOCK, DIAMOND_BLOCK, etc.
muteItemOne: 'GREEN_TERRACOTTA'
muteItemTwo: 'ORANGE_TERRACOTTA'
muteItemThree: 'RED_TERRACOTTA'